#!/bin/sh

xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 75.00 --left-of eDP
xsetroot -cursor_name left_ptr

# autostart
killall sxhkd ; sxhkd &
killall picom ; picom &
killall redshift ; redshift &
feh --bg-fill ~/Pictures/wallpapers/octopus.jpg
$HOME/.config/polybar/launch.sh &

# alises
alias bc='bspc config'
alias br='bspc rule -a'

# workspaces
bspc monitor HDMI-0 -d 1 2 3
bspc monitor eDP    -d 4 5 6

# borders & gaps
bc top_padding           44
bc border_width          8
bc window_gap            8
bc split_ratio           0.50
bc borderless_monocle    true
bc gapless_monocle       true

bc focused_border_color "#1b1f2f"
bc active_border_color  "#0f111a"
bc normal_border_color  "#0f111a"

# rules
br kitty   state=floating
br feh     state=floating
br mpv     state=floating rectangle=854x480+0+0 center=true
br Zathura state=floating rectangle=536x836+0+0 center=true
